export const backend_url = "/"
export const http_url = `http://${backend_url}`
export const websocket_url = `ws://${backend_url}`
export const buttons_url = `/buttons/`
export const settings_url = `/settings/`
export const key_options = `/key-options/`
export const functions = `/functions/`
const currentURL = `${window.location.href}value/`
export const value_ws = currentURL.replace('http://', 'ws://')
