from pynput.keyboard import Key

oa_keys_functions = [
    {"id": 1, "function": "Up"},
    {"id": 2, "function": "Down"},
    {"id": 3, "function": "Right"},
    {"id": 4, "function": "Left"},
    {"id": 5, "function": "Select"},
    {"id": 6, "function": "Back"},
    {"id": 7, "function": "Scroll/rotate left"},
    {"id": 8, "function": "Scroll/rotate right"},
    {"id": 9, "function": "Navigation"},
    {"id": 10, "function": "Answer call"},
    {"id": 11, "function": "Home"},
    {"id": 12, "function": "Media"},
    {"id": 13, "function": "Answer phone"},
    {"id": 14, "function": "End call"},
    {"id": 15, "function": "Toggle play"},
    {"id": 16, "function": "Next track"},
    {"id": 17, "function": "Previous track"},
    {"id": 18, "function": "Google assistant"},
    {"id": 19, "function": "Toggle night mode"},
    {"id": 20, "function": "Mode/toggle between active applications"},
    {"id": 21, "function": "Expand/collapse top bar"},
    {"id": 22, "function": "Volume down"},
    {"id": 23, "function": "Volume up"},
    {"id": 24, "function": "Brightness down"},
    {"id": 25, "function": "Brightness up"},
    {"id": 26, "function": "Toggle mute"},
    {"id": 27, "function": "Bring OpenAuto to front"},
]

functions_list = [
    {"id": 1, "keys": [Key.up]}, 
    {"id": 2, "keys": [Key.down]},
    {"id": 3, "keys": [Key.right]},
    {"id": 4, "keys": [Key.left]},
    {"id": 5, "keys": [Key.enter]},
    {"id": 6, "keys": [Key.esc]},
    {"id": 7, "keys": ['1']},
    {"id": 8, "keys": ['2']},
    {"id": 9, "keys": ['f']},
    {"id": 10, "keys": ['g']},
    {"id": 11, "keys": ['h']},
    {"id": 12, "keys": ['j']},
    {"id": 13, "keys": ['p']},
    {"id": 14, "keys": ['o']},
    {"id": 15, "keys": ['b']},
    {"id": 16, "keys": ['n']},
    {"id": 17, "keys": ['v']},
    {"id": 18, "keys": ['m']},
    {"id": 19, "keys": [Key.f2]},
    {"id": 20, "keys": [Key.ctrl, Key.f3]},
    {"id": 21, "keys": [Key.f6]},
    {"id": 22, "keys": [Key.f7]},
    {"id": 23, "keys": [Key.f8]},
    {"id": 24, "keys": [Key.f9]},
    {"id": 25, "keys": [Key.f10]},
    {"id": 26, "keys": [Key.ctrl, Key.f11]},
    {"id": 27, "keys": [Key.f12]}
]